# Generated by Django 5.0.7 on 2025-06-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school_name',
            new_name='college_name',
        ),
    ]
